/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInvoiceRouteImport } from './routes/api/invoice'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceRoute = ApiInvoiceRouteImport.update({
  id: '/api/invoice',
  path: '/api/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invoice' | '/api/chat' | '/api/invoice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invoice' | '/api/chat' | '/api/invoice'
  id: '__root__' | '/' | '/invoice' | '/api/chat' | '/api/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoiceRoute: typeof InvoiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInvoiceRoute: typeof ApiInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice': {
      id: '/api/invoice'
      path: '/api/invoice'
      fullPath: '/api/invoice'
      preLoaderRoute: typeof ApiInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoiceRoute: InvoiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInvoiceRoute: ApiInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
