/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInvoiceRouteImport } from './routes/api/invoice'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceRoute = ApiInvoiceRouteImport.update({
  id: '/api/invoice',
  path: '/api/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extract': typeof ExtractRoute
  '/invoice': typeof InvoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/invoice': typeof ApiInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extract'
    | '/invoice'
    | '/api/chat'
    | '/api/extract'
    | '/api/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extract'
    | '/invoice'
    | '/api/chat'
    | '/api/extract'
    | '/api/invoice'
  id:
    | '__root__'
    | '/'
    | '/extract'
    | '/invoice'
    | '/api/chat'
    | '/api/extract'
    | '/api/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtractRoute: typeof ExtractRoute
  InvoiceRoute: typeof InvoiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiInvoiceRoute: typeof ApiInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice': {
      id: '/api/invoice'
      path: '/api/invoice'
      fullPath: '/api/invoice'
      preLoaderRoute: typeof ApiInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtractRoute: ExtractRoute,
  InvoiceRoute: InvoiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiInvoiceRoute: ApiInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
